In [1]:
import os



In [2]:
os.getcwd()

'C:\\Anaconda2'

In [4]:
from sklearn.datasets import load_iris

In [5]:
iris = load_iris()

In [7]:
#rnd_clf = RandomForestClassifier(n_estimators=500, n_jobs=-1)
from sklearn.ensemble import RandomForestClassifier

In [8]:
rnd_clf = RandomForestClassifier(n_estimators=500, n_jobs=-1)

In [9]:
rnd_clf.fit(iris["data"], iris["target"])

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=-1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [14]:
print(iris)

{'target_names': array(['setosa', 'versicolor', 'virginica'], 
      dtype='|S10'), 'data': array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.

In [15]:
for name, score in zip(iris["feature_names"], rnd_clf.feature_importances_):
    print(name, score)

('sepal length (cm)', 0.095453489907044567)
('sepal width (cm)', 0.024252702776912542)
('petal length (cm)', 0.44425700287017378)
('petal width (cm)', 0.43603680444586923)


In [18]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

In [19]:
ada_clf = AdaBoostClassifier(
DecisionTreeClassifier(max_depth=1), n_estimators=200,
algorithm="SAMME.R", learning_rate=0.5
)

In [21]:
ada_clf.fit(iris["data"], iris["target"])

AdaBoostClassifier(algorithm='SAMME.R',
          base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=1,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best'),
          learning_rate=0.5, n_estimators=200, random_state=None)

In [23]:
print(ada_clf.get_params,ada_clf.feature_importances_)

(<bound method AdaBoostClassifier.get_params of AdaBoostClassifier(algorithm='SAMME.R',
          base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=1,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best'),
          learning_rate=0.5, n_estimators=200, random_state=None)>, array([ 0.   ,  0.   ,  0.505,  0.495]))


In [24]:
from sklearn.ensemble import GradientBoostingRegressor

In [26]:
gbrt = GradientBoostingRegressor(max_depth=2, n_estimators=3, learning_rate=1.0)
gbrt.fit(iris["data"], iris["target"])

GradientBoostingRegressor(alpha=0.9, init=None, learning_rate=1.0, loss='ls',
             max_depth=2, max_features=None, max_leaf_nodes=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=3, presort='auto',
             random_state=None, subsample=1.0, verbose=0, warm_start=False)

In [27]:
gbrt.feature_importances_

array([ 0.06223134,  0.        ,  0.06593256,  0.8718361 ])

In [29]:
print(gbrt.score)

<bound method GradientBoostingRegressor.score of GradientBoostingRegressor(alpha=0.9, init=None, learning_rate=1.0, loss='ls',
             max_depth=2, max_features=None, max_leaf_nodes=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=3, presort='auto',
             random_state=None, subsample=1.0, verbose=0, warm_start=False)>


In [30]:
from sklearn.decomposition import PCA

In [46]:
pca = PCA(n_components = 4)
X2D = pca.fit_transform(iris["data"])
print(X2D)
print(type(X2D))

[[ -2.68420713e+00  -3.26607315e-01   2.15118370e-02   1.00615724e-03]
 [ -2.71539062e+00   1.69556848e-01   2.03521425e-01   9.96024240e-02]
 [ -2.88981954e+00   1.37345610e-01  -2.47092410e-02   1.93045428e-02]
 [ -2.74643720e+00   3.11124316e-01  -3.76719753e-02  -7.59552741e-02]
 [ -2.72859298e+00  -3.33924564e-01  -9.62296998e-02  -6.31287327e-02]
 [ -2.27989736e+00  -7.47782713e-01  -1.74325619e-01  -2.71468037e-02]
 [ -2.82089068e+00   8.21045110e-02  -2.64251085e-01  -5.00996251e-02]
 [ -2.62648199e+00  -1.70405349e-01   1.58015103e-02  -4.62817610e-02]
 [ -2.88795857e+00   5.70798026e-01  -2.73354061e-02  -2.66154143e-02]
 [ -2.67384469e+00   1.06691704e-01   1.91533300e-01  -5.58909660e-02]
 [ -2.50652679e+00  -6.51935014e-01   6.92749958e-02  -1.66082478e-02]
 [ -2.61314272e+00  -2.15206320e-02  -1.07650353e-01  -1.57704569e-01]
 [ -2.78743398e+00   2.27740189e-01   2.00327788e-01  -7.23508674e-03]
 [ -3.22520045e+00   5.03279909e-01  -6.84136292e-02  -2.19466641e-02]
 [ -2.

In [47]:
pca.components_

array([[ 0.36158968, -0.08226889,  0.85657211,  0.35884393],
       [-0.65653988, -0.72971237,  0.1757674 ,  0.07470647],
       [ 0.58099728, -0.59641809, -0.07252408, -0.54906091],
       [ 0.31725455, -0.32409435, -0.47971899,  0.75112056]])

In [48]:
print(pca.explained_variance_ratio_)

[ 0.92461621  0.05301557  0.01718514  0.00518309]


In [49]:
print(pca.explained_variance_)

[ 4.19667516  0.24062861  0.07800042  0.02352514]


In [54]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print("*******************",A)
print("AT",A.T)
# calculate the mean of each column
M = mean(A.T, axis=1)
print("mean is ",M)
# center columns by subtracting column means
C = A - M
print("!!!!!!!!!!!!!!!!!!!",C)
# calculate covariance matrix of centered matrix
V = cov(C.T)
print(V)
# eigendecomposition of covariance matrix
values, vectors = eig(V)
print(vectors)
print(values)
# project data
P = vectors.T.dot(C.T)
print(P.T)

('*******************', array([[1, 2],
       [3, 4],
       [5, 6]]))
('AT', array([[1, 3, 5],
       [2, 4, 6]]))
('mean is ', array([ 3.,  4.]))
('!!!!!!!!!!!!!!!!!!!', array([[-2., -2.],
       [ 0.,  0.],
       [ 2.,  2.]]))
[[ 4.  4.]
 [ 4.  4.]]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[ 8.  0.]
[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]


In [55]:
#USING PCA

# Principal Component Analysis
from numpy import array
from sklearn.decomposition import PCA
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# create the PCA instance
pca = PCA(2)
# fit on data
pca.fit(A)
# access values and vectors
print(pca.components_)
print(pca.explained_variance_)
# transform data
B = pca.transform(A)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[ 0.70710671  0.70710683]
 [ 0.70710683 -0.70710671]]
[  5.33333349e+00   2.42671684e-16]
[[ -2.82842708e+00  -2.38418579e-07]
 [  0.00000000e+00   0.00000000e+00]
 [  2.82842708e+00   2.38418579e-07]]
